language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "reactjs-coder"
    token:
      secure: "690976c5b51b2aa06be447678c452a6cf796dcc6"
jdk:
  - oraclejdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver