language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "reactjs-coder"
    token:
      secure: "690976c5b51b2aa06be447678c452a6cf796dcc6"
jdk:
  - oraclejdk11
script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=reactjs-coder -Dsonar.login=690976c5b51b2aa06be447678c452a6cf796dcc6
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres